[bell]
animation = "Ease"
command = "None"
duration = 0

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 0

[window.dimensions]
columns = 50
lines = 10

[window.padding]
x = 15
y = 15
